# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181026_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonmodel',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.SchemaModel'),
        ),
    ]
